[package]
name = "crouton"
version = "0.1.0"
edition = "2021"

[dependencies]
crouton-protos = { path = "../crouton-protos" }
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.0", features = ["macros", "process", "sync", "rt-multi-thread"] }
tonic = "0.6.1"
